name: codesight
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24.0
  - pyyaml>=6.0.1
  - chardet>=5.2.0
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.1.0
  - black>=23.0.0
  - flake8>=6.0.0
  - mypy>=1.5.0
  - isort>=5.12.0
  - requests>=2.31.0
  - httpx>=0.25.0
  - pandas>=2.0.0
  - pip:
    - JPype1>=1.4.1
    - faiss-cpu>=1.7.4
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=1.3.0
    - pre-commit>=3.4.0
    - bandit>=1.7.5
    - memory-profiler>=0.61.0
    - line-profiler>=4.1.0
