# CT-HR-STORM Project Configuration for CodeSight Analysis
# Project-specific overrides for the STORM Human Resources Management System

# ==============================================================================
# PROJECT CONFIGURATION
# ==============================================================================
project:
  name: "ct-hr-storm"
  description: "STORM (Staff Training Operations Resource Management) - NBC Universal HR System for television and media production crew scheduling, resource management, and payroll processing"
  source_path: "../../../ct-hr-storm"
  output_path: "projects/ct-hr-storm/output"

# ==============================================================================
# LLM OVERRIDES
# ==============================================================================
llm:
  provider: "kong_aws"
  model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  max_tokens: 8000
  temperature: 0.05

# ==============================================================================
# PIPELINE STEPS OVERRIDES
# ==============================================================================
steps:
  step01:
    include_extensions: [".java", ".jsp", ".jspx", ".vbs", ".js", ".css", ".html", ".xml", ".properties", ".yml", ".yaml", ".sql", ".tld"]
    exclude_patterns: 
      - "**/target/**"
      - "**/build/**" 
      - "**/test/**"
      - "**/node_modules/**"
      - "**/.git/**"
      - "**/bin/**"
      - "**/dist/**"
      - "**/.DS_Store"
      - "**/.vscode/**"
      - "**/.settings/**"
    max_file_size_mb: 30
    enable_framework_detection: true
    framework_confidence_threshold: 0.8
    build_parsers_optional: true

  step02:
    enable_symbol_resolution: true
    parse_javadoc: true
    extract_method_bodies: true
    confidence_threshold: 0.85
    timeout_per_file_seconds: 45

  step04:
    enable_spring_analysis: false
    enable_hibernate_analysis: false
    enable_struts_analysis: true
    enable_servlet: true
    enable_jaxrs: true
    enable_jsp_links: true
    enable_sql_edges_java: true
    enable_sql_edges_jsp: true
    enable_sql_edges_sqlfiles: true
    enable_security_roles: true
    enable_jsp_security_detection: true
    enable_trace_enrichment: true
    enable_business_rules_extraction: true
    config_file_patterns:
      - "**/struts.xml"
      - "**/struts-config.xml"
      - "**/web.xml"
      - "**/validation.xml"
      - "**/validator-rules.xml"
      - "**/tiles-defs.xml"
      - "**/log4j.xml"
      - "**/*.properties"
      - "**/quartz.properties"
    pattern_confidence_threshold: 0.75
    security:
      patterns:
        - "getSecurity"
        - "Security\\."
        - "unauthorizedUse"
        - "<sec:authorize"
        - "<c:if test=\".*role\""
        - '<c:if test="\\$\\{user\\.isAdmin'
        - '<c:if test="\\$\\{user\\.hasRole'
        - "<%.*Security.*%>"
    rules:
      files: ["validation.xml", "validator-rules.xml"]

  step05:
    batch_size: 3
    max_context_length: 12000
    confidence_threshold: 0.7
    enable_business_logic_extraction: true
    enable_domain_classification: true
    retry_attempts: 3
    # Use business domains specific to ct-hr-storm instead of generic labels like UI
    domain_strategy: "always_llm"
    domain_labels:
      - "Employee Management"
      - "Scheduling"
      - "Timekeeping"
      - "Payroll"
      - "Benefits"
      - "Labor Relations"
      - "Contracts"
      - "Skills and Qualifications"
      - "Approvals and Workflow"
      - "Position and Job Management"
      - "Holidays and Calendars"
      - "Overtime and Pay Rules"
      - "Reporting and Analytics"
      - "Security and Access Control"
      - "Administration and Configuration"
      - "Integrations and Interfaces"
    # Create capabilities for routes even if they lack explicit render/handler links
    seed_unlinked_routes: true

# ==============================================================================
# DATABASE OVERRIDES
# ==============================================================================
database:
  # CT-HR-STORM uses db/ directory structure
  discovery_pattern: "db/*"
  logical_name_pattern: "{directory_name_lower}"

# ==============================================================================
# CLASSIFICATION OVERRIDES
# ==============================================================================
classification:
  layers:
    - "UI"
    - "Service"
    - "Database"
    - "Integration"
    - "Configuration"
    - "Reporting"
    - "Utility"
    - "Other"
  confidence_threshold: 0.6
  require_dual_match: true
  fallback_layer: "Other"


# ==============================================================================
# ARCHITECTURAL PATTERNS OVERRIDES
# ==============================================================================
architectural_patterns:
  application: 
    - "**/asl/**"
  business:
    - "**/gsl/**"
  data_access:
    - "**/dsl/**"
    - "**/dsl"
  security:
    - "**/authenticate/**"
    - "**/authenticate"
    - "**/isl/security/**"
    - "**/isl/securityFilter/**"
  shared:
    - "**/isl/**"

# ===============================================================================
# JSP ANALYSIS PATTERNS (ADDED)
# ===============================================================================
jsp_analysis:
  legacy_patterns:
    - "<%[^@!=]"                # Scriptlets (excluding directives, expressions, declarations)
    - "ActiveXObject"           # Use of ActiveX (legacy browser scripting)
    - "VBScript"                # Inline VBScript blocks
    - "document.all"            # Old IE DOM access
    - "document.write"          # Legacy JS
    - "<font "                  # Deprecated HTML tag

  security_tag_patterns:
    - "getSecurity"             # Java security checks in scriptlets
    - "Security\\."             # Security class usage
    - "unauthorizedUse"         # Explicit unauthorized handling
    - "data-permission"
    - "data-role"
    - "<sec:authorize"
    - '<c:if test="\\$\\{user\\.isAdmin'
    - '<c:if test="\\$\\{user\\.hasRole'
    - "<%.*Security.*%>"

  menu_detection:
    - "<UL[^>]*class=[\"']?ULBookClose[\"']?"   # Main menu block
    - "<A[^>]*onclick=['\"]getChildren" # Menu item with JS navigation
    - "<nav"
    - "<div[^>]*id=[\"']mainMenu[\"']"
    - "<tiles:insertDefinition name=\"main.menu\""
    - "<c:forEach var=\"menuItem\""
    - "<iframe[^>]*id=[\"']Contents[\"']?"
    - "<B ID=Title>"

  service_invocation_hints:
    - "resourceMgrObject"
    - "messageMgr"
    - "SessionHandler"
    - "xhtmlHandlerObject"
    - "getNameFromDB"
    - "getSession"
    - "getUserId"
    - "getUserCompanyId"
    - "getResourceIdForVacation"
    - "getResourceIdForAssignments"
    - "getHasIMessages"
    - "getMessageByUserId"
    - "stormContext"
    - "ScheduleXHTMLHandler"
    - '\\$\\{.*Service\.'
    - '\\$\\{.*Manager\.'

  tiles_patterns:
    - "<tiles:insertDefinition"
    - "<tiles:putAttribute"
    - "<tiles:definition"

  custom_tag_prefixes:
    - "hr:"
    - "storm:"
    - "tiles:"

  exclude_paths:
    - "**/test/**"
    - "**/legacy/**"
  include_paths:
    - "**/*.jsp"
    - "**/*.jspx"

# ==============================================================================
# LANGUAGE PATTERNS OVERRIDES
# ==============================================================================
languages_patterns:
  fallback:
    UI: ["*Controller*", "*Handler*", "*Servlet*", "*.jsp", "*.js", "*.html", "*.css", "*View*"]
    Service: ["*Service*", "*Manager*", "*Processor*", "*Business*", "*Logic*", "*Workflow*"]
    Database: ["*DAO*", "*Repository*", "*Entity*", "*Model*", "*Mapper*"]
    Integration: ["*Client*", "*Connector*", "*Adapter*", "*Gateway*", "*API*"]
    Configuration: ["*.properties", "*.xml", "*.yaml", "*.yml", "*Config*", "*Configuration*"]
    Utility: ["*Util*", "*Helper*", "*Common*", "*Shared*"]

  java:
    indicators:
      UI: 
        - "Action"
        - "Servlet"
        - "Handler"
        - "@WebServlet"
        - "*Controller*"
        - "XHTMLHandler"
        - "XHTMLInterface"
        - "XHTMLEncoder"
        - "xhtml"
      Service:
        - "Manager"
        - "Handler"
        - "@Service"
        - "*Business*"
        - "*Processor*"
        - "*Workflow*"
      Database:
        - "DAO"
        - "Mgr"
        - "@Entity"
        - "*Repository*"
        - "*Mapper*"
        - "entity"
        - "entitymgmt"
      Integration:
        - "Client"
        - "Adapter"
        - "Gateway"
        - "*GIS*"
        - "*WebService*"
        - "*I213*"
        - "*I70*" 
        - "*I90*"
        - "*NetRM*"
        - "*Quartz*"
        - "ActiveXObject"
        - "Microsoft.XMLHTTP"
      Reporting:
        - "Report"
        - "*Report*"
        - "BaseReport"
        - "ReportsHandler"
        - "ReportsMgr"
        - "ReportsVO"
      Configuration:
        - "@Configuration"
        - "@ConfigurationProperties"
    package_patterns:
      UI: 
        - "com.nbcuni.dcss.storm.**.action.**"
        - "com.nbcuni.dcss.storm.**.servlet.**"
        - "com.nbcuni.dcss.storm.isl.xhtml.**"
      Service:
        - "com.nbcuni.dcss.storm.asl.**"
        - "com.nbcuni.dcss.storm.gsl.**"
      Database:
        - "com.nbcuni.dcss.storm.dsl.**"
        - "com.nbcuni.dcss.storm.**.dao.**"
      Integration:
        - "com.nbcuni.dcss.storm.gis.**"
        - "com.nbcuni.dcss.storm.**.client.**"
        - "com.nbcuni.dcss.storm.dsl._i213srvc.**"
        - "com.nbcuni.dcss.storm.dsl._i70srvc.**"
        - "com.nbcuni.dcss.storm.dsl._i90srvc.**"
        - "com.nbcuni.dcss.storm.dsl._netrmhandlers.**"
        - "com.nbcuni.dcss.storm.quartz.**"
      Reporting:
        - "com.nbcuni.dcss.storm.core.**"
        - "com.nbcuni.dcss.storm.gsl.reports.**"
        - "com.nbcuni.dcss.storm.asl.reporting.**"
        - "com.nbcuni.dcss.storm.core.Report.**"
      Configuration:
        - "com.inbcu.storm.api.config.**"
        - "com.nbcuni.dcss.storm.isl.config.**"
      Utility:
        - "com.nbcuni.dcss.storm.isl.utils.**"
        - "com.nbcuni.dcss.storm.isl.**"

  javascript:
    indicators:
      UI: 
        - "Component"
        - "View"
        - "Page"
        - "Route"
        - "ActiveXObject"
        - "Microsoft.XMLHTTP"
        - "EXCEL.application"
      Service: 
        - "Service"
        - "API"
        - "Handler"
        - "Manager"
      Database: 
        - "Model"
        - "Schema"
        - "Repository"
      Integration: 
        - "Client"
        - "Adapter"
        - "Connector"
        - "ActiveXObject"
    path_patterns:
      UI: ["**/components/**", "**/pages/**"]
      Service: ["**/services/**"]
      Database: ["**/models/**"]
      Integration: ["**/api/**"]

  jsp:
    indicators:
      UI: 
        - "<%@"
        - "<%="
        - "<%!"
        - "<jsp:"
        - "<c:"
        - "<f:"
        - "<html>"
        - "<body>"
        - "ActiveXObject"
        - "Microsoft.XMLHTTP"
        - "EXCEL.application"
      Service: 
        - "<%"
        - "import="
        - "session."
        - "request."
      Database: 
        - "sql"
        - "jdbc"
        - "connection"
        - "resultset"
      Integration: 
        - "client"
        - "webservice"
        - "api"
        - "ActiveXObject"
    path_patterns:
      UI: ["**/*.jsp", "**/*.jspx"]

  vbscript:
    indicators:
      UI: 
        - "SCRIPT FOR="
        - "EVENT="
        - "FOR=window EVENT="
        - "FOR=Button"
        - "language=vbscript"
        - "LANGUAGE=VBScript"
        - "Sub "
        - "Function "
        - "Dim "
    path_patterns:
      UI: ["**/*.jsp", "**/*.jspx", "**/*.html", "**/*.htm"]

# ==============================================================================
# FRAMEWORKS OVERRIDES  
# ==============================================================================
frameworks:
  struts:
    indicators: 
      - "Action"
      - "ActionForm"
      - "struts"
      - "StormSimpleAction"
      - "extends ActionSupport"
    layer_mapping:
      "Action": "UI"
      "ActionForm": "UI"
      "Handler": "Service"
      "Manager": "Service"
      "DAO": "Database"
      "Service": "Service"
      "Exception": "Utility"
    config_files: 
      - "struts.xml"
      - "struts-config.xml"
      - "web.xml"
      - "validation.xml"
      - "validator-rules.xml"
      - "tiles-defs.xml"
  
  jee:
    indicators:
      - "@Stateless"
      - "@Stateful" 
      - "@Entity"
      - "@WebServlet"
      - "@EJB"
      - "HttpServlet"
    layer_mapping:
      "@WebServlet": "UI"
      "@ManagedBean": "UI"
      "@Stateless": "Service"
      "@Stateful": "Service"
      "@Entity": "Database"
      "@EJB": "Service"
      "@MessageDriven": "Integration"
      "@WebService": "Integration"
    config_files:
      - "web.xml"
      - "ejb-jar.xml"
      - "persistence.xml"
      - "application.xml"

quality_gates:
  step01:
    unix_relative_required: true
    min_config_accessible_pct: 0.9
  step02:
    min_parse_success_pct: 0.75
    min_route_handler_resolution_pct: 0.5
    max_unresolved_refs_pct: 0.2
  step03:
    min_embedding_coverage_pct: 0.85
    min_cluster_cohesion: 0.5
  step04:
    min_config_parse_success_pct: 0.75
    min_pattern_confidence: 0.75
  step05:
    min_citations_per_capability: 1
    min_capability_coverage_pct: 0.4
  step06:
    min_route_chain_coverage_pct: 0.6
    require_iam_for_guarded_routes: false
