# CT-HR-STORM-TEST Project Configuration for CodeSight Analysis
# Project-specific overrides for the STORM Human Resources Management System (Test Project)

# ==============================================================================
# PROJECT CONFIGURATION
# ==============================================================================
project:
  name: "ct-hr-storm-test"
  description: "STORM (Staff Training Operations Resource Management) - NBC Universal HR System for television and media production crew scheduling, resource management, and payroll processing (Test Project)"
  source_path: "../../test/test-projects/ct-hr-storm-test"
  output_path: "projects/ct-hr-storm-test/output"

# ==============================================================================
# LLM OVERRIDES
# ==============================================================================
llm:
  provider: "kong_aws"
  model: "anthropic.claude-3-5-sonnet-20241022-v2:0"
  max_tokens: 8000
  temperature: 0.05

# ==============================================================================
# PIPELINE STEPS OVERRIDES
# ==============================================================================
steps:
  step01:
    include_extensions: [".java", ".jsp", ".jspx", ".vbs", ".js", ".css", ".html", ".xml", ".properties", ".yml", ".yaml", ".sql", ".tld"]
    exclude_patterns: 
      - "**/target/**"
      - "**/build/**" 
      - "**/test/**"
      - "**/node_modules/**"
      - "**/.git/**"
      - "**/bin/**"
      - "**/dist/**"
      - "**/.DS_Store"
      - "**/.vscode/**"
      - "**/.settings/**"
    max_file_size_mb: 30
    enable_framework_detection: true
    framework_confidence_threshold: 0.8

  step02:
    enable_symbol_resolution: true
    parse_javadoc: true
    extract_method_bodies: true
    confidence_threshold: 0.85
    timeout_per_file_seconds: 45

  step04:
    enable_spring_analysis: false
    enable_hibernate_analysis: false
    enable_struts_analysis: true
    config_file_patterns:
      - "**/struts.xml"
      - "**/struts-config.xml" 
      - "**/web.xml"
      - "**/validation.xml"
      - "**/validator-rules.xml"
      - "**/tiles-defs.xml"
      - "**/log4j.xml"
      - "**/*.properties"
      - "**/quartz.properties"
    pattern_confidence_threshold: 0.75
    enable_jsp_security_detection: true
    security:
      patterns:
        - "getSecurity"
        - "Security\\."
        - "unauthorizedUse"
        - "<sec:authorize"
        - "<c:if test=\".*role\""

  step05:
    batch_size: 3
    max_context_length: 12000
    confidence_threshold: 0.7
    enable_business_logic_extraction: true
    enable_domain_classification: true
    retry_attempts: 3

# ==============================================================================
# CLASSIFICATION OVERRIDES
# ==============================================================================
classification:
  layers:
    - "UI"
    - "Service"
    - "Database"
    - "Integration"
    - "Configuration"
    - "Reporting"
    - "Utility"
    - "Other"
  confidence_threshold: 0.6
  require_dual_match: true
  fallback_layer: "Other"


# ==============================================================================
# ARCHITECTURAL PATTERNS OVERRIDES
# ==============================================================================
architectural_patterns:
  application: 
    - "**/asl/**"
  business:
    - "**/gsl/**"
  data_access:
    - "**/dsl/**"
    - "**/dsl"
  security:
    - "**/authenticate/**"
    - "**/authenticate"
    - "**/isl/security/**"
    - "**/isl/securityFilter/**"
  shared:
    - "**/isl/**"

# ==============================================================================
# LANGUAGE PATTERNS OVERRIDES
# ==============================================================================
languages_patterns:
  fallback:
    UI: ["*Controller*", "*Handler*", "*Servlet*", "*.jsp", "*.js", "*.html", "*.css", "*View*"]
    Service: ["*Service*", "*Manager*", "*Processor*", "*Business*", "*Logic*", "*Workflow*"]
    Database: ["*DAO*", "*Repository*", "*Entity*", "*Model*", "*Mapper*"]
    Integration: ["*Client*", "*Connector*", "*Adapter*", "*Gateway*", "*API*"]
    Configuration: ["*.properties", "*.xml", "*.yaml", "*.yml", "*Config*", "*Configuration*"]
    Utility: ["*Util*", "*Helper*", "*Common*", "*Shared*"]

  java:
    indicators:
      UI: 
        - "Action"
        - "Servlet"
        - "Handler"
        - "@WebServlet"
        - "*Controller*"
        - "XHTMLHandler"
        - "XHTMLInterface"
        - "XHTMLEncoder"
        - "xhtml"
      Service:
        - "Manager"
        - "Handler"
        - "@Service"
        - "*Business*"
        - "*Processor*"
        - "*Workflow*"
        - "*MgrObject"
        - "static.*MgrObject()"
        - "*Handler*"
        - "TimeKeeper*Handler"
        - "*Orchestrat*"
      Database:
        - "DAO"
        - "Mgr"
        - "@Entity"
        - "*Repository*"
        - "*Mapper*"
        - "entity"
        - "entitymgmt"
        - "extends EntityMgr"
        - "implements I.*Mgr"
        - "*MgrObject"
        - "EntityMgr"
      Integration:
        - "Client"
        - "Adapter"
        - "Gateway"
        - "*GIS*"
        - "*WebService*"
        - "*I213*"
        - "*I70*" 
        - "*I90*"
        - "*NetRM*"
        - "*Quartz*"
        - "ActiveXObject"
        - "Microsoft.XMLHTTP"
      Reporting:
        - "Report"
        - "*Report*"
        - "BaseReport"
        - "ReportsHandler"
        - "ReportsMgr"
        - "ReportsVO"
      Configuration:
        - "@Configuration"
        - "@ConfigurationProperties"
    package_patterns:
      UI: 
        - "com.nbcuni.dcss.storm.**.action.**"
        - "com.nbcuni.dcss.storm.**.servlet.**"
        - "com.nbcuni.dcss.storm.isl.xhtml.**"
        - "com.nbcuni.dcss.storm.**.xhtml.**"
      Service:
        - "com.nbcuni.dcss.storm.asl.**"
        - "com.nbcuni.dcss.storm.gsl.**"
        - "com.nbcuni.dcss.storm.isl.entitymgmt.**"
        - "com.nbcuni.dcss.storm.isl.utils.**"
      Database:
        - "com.nbcuni.dcss.storm.dsl.**"
        - "com.nbcuni.dcss.storm.**.dao.**"
        - "com.nbcuni.dcss.storm.**.entitymgmt.**"
      Integration:
        - "com.nbcuni.dcss.storm.gis.**"
        - "com.nbcuni.dcss.storm.**.client.**"
        - "com.nbcuni.dcss.storm.dsl._i213srvc.**"
        - "com.nbcuni.dcss.storm.dsl._i70srvc.**"
        - "com.nbcuni.dcss.storm.dsl._i90srvc.**"
        - "com.nbcuni.dcss.storm.dsl._netrmhandlers.**"
        - "com.nbcuni.dcss.storm.quartz.**"
      Reporting:
        - "com.nbcuni.dcss.storm.core.**"
        - "com.nbcuni.dcss.storm.gsl.reports.**"
        - "com.nbcuni.dcss.storm.asl.reporting.**"
        - "com.nbcuni.dcss.storm.core.Report.**"
      Configuration:
        - "com.inbcu.storm.api.config.**"
        - "com.nbcuni.dcss.storm.isl.config.**"
      Utility:
        - "com.nbcuni.dcss.storm.isl.utils.**"
        - "com.nbcuni.dcss.storm.isl.**"
    entity_manager_patterns:
      file_name_pattern: "**/*Mgr.java"
      class_declaration_pattern: "class\\s+(\\w+Mgr)\\s+extends\\s+EntityMgr"
      table_name_method_pattern: "protected\\s+String\\s+getTableName\\(\\)\\s*\\{"
    sql_execution_patterns:
      prepared_statement_pattern: "new\\s+StormPS\\s*\\(\\s*\"([^\";]+)\""
      exec_pattern: "(?i)(?:EXEC\\s+)?(\\w+)(?:\\s+\\?|\\s*$)"
      dynamic_sp_pattern: "getTableName\\(\\)\\s*\\+\\s*\"(\\w+)\""

  javascript:
    indicators:
      UI: 
        - "Component"
        - "View"
        - "Page"
        - "Route"
        - "ActiveXObject"
        - "Microsoft.XMLHTTP"
        - "EXCEL.application"
      Service: 
        - "Service"
        - "API"
        - "Handler"
        - "Manager"
      Database: 
        - "Model"
        - "Schema"
        - "Repository"
      Integration: 
        - "Client"
        - "Adapter"
        - "Connector"
        - "ActiveXObject"
    path_patterns:
      UI: ["**/components/**", "**/pages/**"]
      Service: ["**/services/**"]
      Database: ["**/models/**"]
      Integration: ["**/api/**"]

  jsp:
    indicators:
      UI: 
        - "<%@"
        - "<%="
        - "<%!"
        - "<jsp:"
        - "<c:"
        - "<f:"
        - "<html>"
        - "<body>"
        - "ActiveXObject"
        - "Microsoft.XMLHTTP"
        - "EXCEL.application"
      Service: 
        - "<%"
        - "import="
        - "session."
        - "request."
      Database: 
        - "sql"
        - "jdbc"
        - "connection"
        - "resultset"
      Integration: 
        - "client"
        - "webservice"
        - "api"
        - "ActiveXObject"
    path_patterns:
      UI: ["**/*.jsp", "**/*.jspx"]

  vbscript:
    indicators:
      UI: 
        - "SCRIPT FOR="
        - "EVENT="
        - "FOR=window EVENT="
        - "FOR=Button"
        - "language=vbscript"
        - "LANGUAGE=VBScript"
        - "Sub "
        - "Function "
        - "Dim "
    path_patterns:
      UI: ["**/*.jsp", "**/*.jspx", "**/*.html", "**/*.htm"]

# ============================================================================
# FRAMEWORKS OVERRIDES  
# ============================================================================
frameworks:
  storm:
    indicators:
      - "Mgr"
      - "I*Mgr"
      - "*MgrObject"
      - "EntityMgr"
      - "extends EntityMgr"
      - "implements I.*Mgr"
      - "XHTMLHandler"
      - "StormSimpleAction"
    layer_mapping:
      "Mgr": "Database"
      "Handler": "Service"
      "XHTMLHandler": "UI"
      "Action": "UI"
      "EntityMgr": "Database"
    config_files:
      - "**/*.properties"
      - "**/web.xml"
      - "**/log4j.xml"
      - "**/quartz.properties"
      
  struts:
    indicators: 
      - "Action"
      - "ActionForm"
      - "struts"
      - "StormSimpleAction"
      - "extends ActionSupport"
      - "extends Action"
    layer_mapping:
      "Action": "UI"
      "ActionForm": "UI"
      "Handler": "Service"
      "Manager": "Service"
      "Mgr": "Database"
      "DAO": "Database"
      "Service": "Service"
      "Exception": "Utility"
    config_files: 
      - "struts.xml"
      - "struts-config.xml"
      - "web.xml"
      - "validation.xml"
      - "validator-rules.xml"
      - "tiles-defs.xml"
  
  jee:
    indicators:
      - "@Stateless"
      - "@Stateful" 
      - "@Entity"
      - "@WebServlet"
      - "@EJB"
      - "HttpServlet"
    layer_mapping:
      "@WebServlet": "UI"
      "@ManagedBean": "UI"
      "@Stateless": "Service"
      "@Stateful": "Service"
      "@Entity": "Database"
      "@EJB": "Service"
      "@MessageDriven": "Integration"
      "@WebService": "Integration"
    config_files:
      - "web.xml"
      - "ejb-jar.xml"
      - "persistence.xml"
      - "application.xml"

# =============================================================================
# JSP ANALYSIS PATTERNS (ADDED)
# =============================================================================
jsp_analysis:
  legacy_patterns:
    - "<%[^@!=]"                # Scriptlets (excluding directives, expressions, declarations)
    - "ActiveXObject"           # Use of ActiveX (legacy browser scripting)
    - "VBScript"                # Inline VBScript blocks
    - "document.all"            # Old IE DOM access
    - "document.write"          # Legacy JS
    - "<font "                  # Deprecated HTML tag

  security_tag_patterns:
    - "getSecurity"             # Java security checks in scriptlets
    - "Security\\."             # Security class usage
    - "unauthorizedUse"         # Explicit unauthorized handling
    - "data-permission"
    - "data-role"
    - "<sec:authorize"
    - "<c:if test=\"\\$\\{user\\.isAdmin"
    - "<c:if test=\"\\$\\{user\\.hasRole"
    - "<%.*Security.*%>"

  menu_detection:
    - "<UL[^>]*class=[\"']?ULBookClose[\"']?"   # Main menu block
    - "<A[^>]*onclick=['\"]getChildren" # Menu item with JS navigation
    - "<nav"
    - "<div[^>]*id=[\"']mainMenu[\"']"
    - "<tiles:insertDefinition name=\"main.menu\""
    - "<c:forEach var=\"menuItem\""
    - "<iframe[^>]*id=[\"']Contents[\"']?"
    - "<B ID=Title>"

  service_invocation_hints:
    - "resourceMgrObject"
    - "messageMgr"
    - "SessionHandler"
    - "xhtmlHandlerObject"
    - "getNameFromDB"
    - "getSession"
    - "getUserId"
    - "getUserCompanyId"
    - "getResourceIdForVacation"
    - "getResourceIdForAssignments"
    - "getHasIMessages"
    - "getMessageByUserId"
    - "stormContext"
    - "ScheduleXHTMLHandler"
    - '\$\{.*Service\.'
    - '\$\{.*Manager\.'

  tiles_patterns:
    - "<tiles:insertDefinition"
    - "<tiles:putAttribute"
    - "<tiles:definition"

  custom_tag_prefixes:
    - "hr:"
    - "storm:"
    - "tiles:"

  exclude_paths:
    - "**/test/**"
    - "**/legacy/**"
  include_paths:
    - "**/*.jsp"
    - "**/*.jspx"

